package com.accenture.document_sync_service.notification.template;

import com.accenture.document_sync_service.notification.model.ExecutionSummary;

public abstract class AbstractEmailTemplateBuilder
        implements EmailTemplateBuilder {

    protected void appendHeader(StringBuilder html) {

        html.append("""
                <!DOCTYPE html>
                <html>
                <head>
                    <meta charset="UTF-8">
                    <style>

                        body{
                            font-family:Arial,Helvetica,sans-serif;
                            background:#f4f6f8;
                            margin:0;
                            padding:30px;
                        }

                        .container{
                            max-width:900px;
                            margin:auto;
                            background:white;
                            border-radius:8px;
                            overflow:hidden;
                            box-shadow:0 2px 8px rgba(0,0,0,0.1);
                        }

                        .header{
                            background:#003366;
                            color:white;
                            padding:20px;
                            text-align:center;
                        }

                        .section{
                            padding:20px;
                        }

                        h2{
                            color:#003366;
                            margin-bottom:10px;
                        }

                        table{
                            width:100%;
                            border-collapse:collapse;
                        }

                        th,td{
                            border:1px solid #dddddd;
                            padding:10px;
                            text-align:left;
                        }

                        th{
                            background:#eeeeee;
                        }

                    </style>
                </head>

                <body>

                <div class="container">

                <div class="header">
                    <h1>Document Sync Service</h1>
                    <p>Execution Report</p>
                </div>
                """);
    }

    protected void appendFooter(StringBuilder html) {

        html.append("""
                <div class="section"
                     style="
                         text-align:center;
                         color:#666666;
                         font-size:12px;
                         border-top:1px solid #dddddd;
                         margin-top:20px;
                         padding-top:20px;">

                    <p>
                        This is an automated email generated by the
                        Document Sync Service.
                    </p>

                    <p>
                        Please do not reply to this email.
                    </p>

                </div>

                </div>

                </body>
                </html>
                """);
    }

    protected void appendRow(
            StringBuilder html,
            String label,
            String value) {

        html.append("""
                <tr>
                    <th style="width:35%;">
                """)
                .append(label)
                .append("""
                            </th>
                            <td>
                        """)
                .append(value == null ? "-" : value)
                .append("""
                            </td>
                        </tr>
                        """);
    }

    protected void appendCell(
            StringBuilder html,
            String value) {

        html.append("<td>")
                .append(value == null ? "-" : value)
                .append("</td>");
    }

    protected void appendExecutionSummary(
            StringBuilder html,
            ExecutionSummary summary) {

        html.append("""
                <div class="section">

                    <h2>Execution Summary</h2>

                    <table>
                """);

        appendRow(html, "Job Status", summary.getStatus().name());
        appendRow(html, "Environment", summary.getEnvironment().name());
        appendRow(html, "Trigger", summary.getTrigger().name());

        appendRow(html, "Started At",
                String.valueOf(summary.getStartedAt()));

        appendRow(html, "Completed At",
                String.valueOf(summary.getCompletedAt()));

        appendRow(html, "Duration",
                String.valueOf(summary.getDuration()));

        html.append("""
                    </table>

                </div>
                """);
    }

}