spring:
  application:
    name: document-sync-service

  profiles:
    active: dev

server:
  port: ${PORT:8080}

document-sync:
  scheduler:
    retry-limit: 3
    fixed-delay: 60000

gcp:
  storage:
    project-id: docusignsync
    bucket-name: document-sync-demo
    credentials-path: "C:/DocuSignKeys/docusignsync-8fbeb99824c8.json"

logging:
  level:
    root: INFO
    com.accenture.documentsync: DEBUG