spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

gcp:
  storage:
    project-id: ${GCP_PROJECT_ID}
    bucket-name: ${GCP_BUCKET_NAME}

docusign:
  integration-key: ${DOCUSIGN_INTEGRATION_KEY}
  user-id: ${DOCUSIGN_USER_ID}
  account-id: ${DOCUSIGN_ACCOUNT_ID}
  base-url: ${DOCUSIGN_BASE_URL}
  oauth-base-url: ${DOCUSIGN_OAUTH_BASE_URL}
  private-key-path: ${DOCUSIGN_PRIVATE_KEY_PATH}
